### ISSUE TITLE
Sprint0 Checklist

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ServicePrincipal#10]
# Sprint0 Checklist

## Tooling
- [X] Setup/Configure Azure Subscriptions  (4.co)
- [x] CD Tooling (GitHub Actions) 
- [X] Work Item tracking Tooling (GitHub) 
- [X] Collaboration and Communication Tooling  (Teams)
- [X] Share user lists for Azure AD 
- [X] Share user lists for Source Control

## Planning
- [X] Define success criteria 
- [X] Customer requirements
- [X] Customer Team identified
- [X] Microsoft Team identified 
- [x] Architecture Review Process

## Execution
- [x] Sprint 0 plan (all stories and all features)
- [X] Sprint Plan (Weekly sprints)
- [X] Onsite plan (N/A)
- [X] Repo Policies (Main, 1 approver, Team access) 
- [X] Branch Management (1 approver, SLA 12hrs)
- [x] Scrum ceremonies scheduled (Standups: M, T, W 10-10:30;  Review/Retro: Thurs 9:30-10:30, Sprint: Friday-Wed)

## Next Steps
- [x] Create doc folder 
- [x] Standup. Review/Retro, Planning meetings sent
- [x] Update templates
- [x] Update tags
- [x] Define User Stories in repo
- [x] Working Agreement (document)
