### ISSUE TITLE
Get Full Path Deployment Working

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ServicePrincipal#117]
## Description:
- [x] deploy as container to Function App
- [x] add test Function method to prove deployment externally
- [x] modify terraform to deploy container based Function App
