### ISSUE TITLE
Service Principal: Tracking DoD

### ISSUE THREAD

**Issue by devorekristen** [retaildevcrews/ServicePrincipal#118]
## Description

As an AAD Administrator, I would like to query the current state of Service Principals and their change history so that I may find the business owner of an object and review changes made to the Service Principal over time.

## Acceptance Criteria
- [ ] Query Service Principal information from an external store and see the current state of Service Principals in my AAD tenet
- [ ] Query the changes made to a Service Principal over time

## Definition of Done
- [x] Code changes reviewed & signed off 
- [x] Existing documentation is updated (readme, .md's) 
- [ ] New documentation needed to support the change is created 
- [ ] Code changes checked into main 
- [ ] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed 
- [x] CI completes successfully 
- [x] CD completes successfully 
- [ ] New changes in smoke test for 48hrs (ongoing) 
- [ ] Create task for required artifacts 

Engineering Playbook [Definition of Done](https://github.com/microsoft/code-with-engineering-playbook/blob/master/team-agreements/definition-of-done/readme.md)
