### ISSUE TITLE
Design New Partition Keys for Tracking and Audit Collections

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ServicePrincipal#127]
## Description:
Currently, both collections have `id` specified as the partition key.  However, the `id` field will come from the AAD Object Id field and isn't likely a suitable partition key.

We need to:
- [ ] Define partition keys for both collections
- [ ] Update DAL and consumers to use correct parition keys
- [ ] Update deployed infrastructure (delete and recreate collections)
- [ ] Update Terraform scripts
- [ ] Update [Data Dictionary](https://microsoft.sharepoint.com/:x:/t/WMTCSEEngagement/EWkbBOJXRTxAoHt_ereBrM0BMC3tCL228ymV2qY7LqfVeg?e=gCrkuK)

Blocks #68
