### ISSUE TITLE
Engineering Fundamentals Checklist

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ServicePrincipal#130]
# Tech Lead's Engineering Fundamentals Checklist

This checklist helps to ensure that our projects meet our Engineering Fundamentals.

## Source Control

- [x] The main branch is locked.
- [x] Merges are done through PRs.
- [x] PRs reference related work items.
- [x] Commit history is consistent and commit messages are informative (what, why).
- [ ] Secrets are not part of the commit history or made public. (see [Credential scanning]())
N/A Public repositories follow the [OSS guidelines](), see `Required files in default branch for public repositories`.

More details on [Source Control]()

## Work Item Tracking

- [X] All items are tracked in GitHub
- [X] The board is organized (swim lanes, feature tags, technology tags).

## Testing

- [ ] Unit tests cover the majority of all components (>90% if possible).
- [X] Integration tests run to test the solution e2e.

More details on [Unit Testing](automated-testing/unit-testing/readme.md)

## CI/CD

- [x] Project runs CI with automated build and test on each PR.
- [X] Project uses CD to manage deployments to a replica environment before PRs are merged.
- [x] Main branch is always shippable.

## Security - TO DO

- [x] Access control.
- [x] Separation of concerns.
- [x] Robust treatment of secrets.
- [x] Encryption for data in transit (and if necessary at rest) and password hashing.

## Observability -- CSE isn't configuring analytics due to customer deployment

- [ ] Significant business and functional events are tracked and related metrics collected.
- [X] Application faults and errors are logged.
- [ ] Health of the system is monitored.
- [ ] The client and server side observability data can be differentiated.
- [X] Logging configuration can be modified without code changes (eg: verbose mode).
- [ ] [Incoming tracing context]() is propagated to allow for production issue debugging purposes.
- [ ] GDPR compliance is ensured regarding PII (Personally Identifiable Information).

## Agile/Scrum

- [x] Process Lead (fixed/rotating) to run standup daily.
- [x] Agile process clearly defined within team.
- [x] Tech Lead (+ PO/Others) have responsibility for backlog management and grooming.
- [x] Working agreement between members of team and customer.

## Design Reviews

- [X] Process for conducting design reviews is included in the [Working Agreement]( )
- [X] Design reviews for each major component of the solution are carried out and documented, including alternatives.
- [X] Stories and/or PRs link to the design document.
- [X] Each user story includes a task for design review by default, which is assigned or removed during sprint planning.
- [X] Project advisors are invited to design reviews or asked to give feedback to the design decisions captured in documentation.
- [X] Discover all the reviews that the customer's processes require and plan for them.

## Code Reviews

- [X] Clear agreement in the team as to function of code reviews.
- [X] Code review checklist or established process.
- [X] A minimum number of reviewers (usually 2) for a PR merge is enforced by policy. (1 due to size of team)
- [X] Linters/Code Analyzers, unit tests and successful builds for PR merges are set up.
- [X] Process to enforce a quick review turnaround.

More details on [Code Reviews]()

## Retrospectives

- [X] Set time for retrospectives each week/at the end of each sprint.
- [X] 1-3 proposed experiments to be tried each week/sprint to improve the process.
- [X] Experiments have owners and are added to project backlog.
- [X] Longer retrospective for Milestones and project completion.

More details on [Retrospectives]()

## Engineering Feedback

- [x] Submit business and technical blockers that prevent project success
- [x] Add suggestions for improvements to leveraged services and components
- [x] Ensure feedback is detailed and repeatable

More details on [Engineering Feedback]()
