### ISSUE TITLE
Enhanced Discovery

### ISSUE THREAD

**Issue by jkeane** [retaildevcrews/ServicePrincipal#291]
- [ ] Create RunHistory collection, Run model, RunHistoryRepository, RunHistoryService
- [ ] Change HttpTrigger to post to queue and return run id
- [ ] Add HttpTrigger function to retrieve status of processor (with semver) with optional run id

Reference: #295
