### ISSUE TITLE
ObjectTracking Service

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ServicePrincipal#42]
## Description:
We need to create DAL components that may be used in conjunction with the CosmosDB connection component to read and write records to the ObjectTracking collection.

- [ ] create POCO to represent ObjectTracking documents
- [ ] create DAL with methods to retrieve and update by id
- [ ] create DAL method to create new record

Predecessor: #41 
References: #12, #51
