### ISSUE TITLE
Audit Service

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ServicePrincipal#68]
## Description:
Predecessors: #43

NOTE: No sensitive attribute values may be emitted into audit log unencrypted (if at all)

- [x] Register audit service interface and concrete in IoC container during application bootstrap
- [ ] Register audit service settings POCO in IoC container during application bootstrap
- [ ] Inject audit service settings POCO into audit service
- [x] Inject audit service interface into client components (ServicePrincipalProcessor, ...)
- [x] Audit Types: CHANGE, FAIL, PASS

CHANGE Audit
	1. Id of Object
	2. Name of Object Attribute being changed
	3. Existing value of attribute
	4. New Value of Attribute
	5. Reason for Change
	
FAIL Audit
	1. Id of Object
	2. Name of Object Attribute failing audit check
	3. Existing Value of Object Attribute
	4. Reason for Fail

PASS Audit
	1. Id of Object
	2. Name of Object Attribute passing audit check
	3. Existing Value of Object Attribute
	4. Reason for Pass
