### ISSUE TITLE
Add Function Stubs for Queue Triggers

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ServicePrincipal#69]
## Description:
- [ ] We need to add two methods to the GraphDeltaProcessor class:
      1.  Function to trigger from "cosmosupdatequeue" and will be used to write updates to the ObjectTracking and Audit collections
      2.  Function to trigger from "aadupdatequeue" and will be used to write updates back to AAD

- [ ] They should use the Azure Functions trigger and bind to the required configuration for each
- [ ] Configuration data should be stored in KeyVault secrets and retrieved by the Function for execution
- [ ] Stored secrets need to be documented in the [wiki](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/tab::f9c11dec-9945-4a70-a3ce-d0f7b9246c21?context=%7B%22subEntityId%22%3A%22%7B%5C%22pageId%5C%22%3A4%2C%5C%22sectionId%5C%22%3A6%2C%5C%22origin%5C%22%3A2%7D%22%2C%22channelId%22%3A%2219%3Ad02cbbf18e0a4bf3b0511ac4f5ef9228%40thread.skype%22%7D&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
