### ISSUE TITLE
Service Principal - CPR - September 2020

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ServicePrincipal#7]
## Service Principal: September Checkpoint Review

- M0, September 2020
- September 9, 2020

### "DoneLog" Review

- [x] What was planned to be done this month?
 - Our main focus this month was completing Sprint 0 tasks, developing an agreed upon game plan with initial spikes and setting up engagement infrastructure. 

- [x] What was actually done this month?
- Team filed CSE Feedback as there is currently no way to associate a Business Owner with a Service Principal, which can lead to security and operational issues  [CSE Feedback](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/385372/)

- Team completed Sprint 0 checklist (#10)

  - Ensures appropriate tooling and engineering fundamentals set-up
  - Gain agreement on customer requirements and success criteria
  - Team working agreement and execution plan
  
 - Initial user stories defined (#11, #12)

 - Initial scaffolding set-up (#4)

- Team did spikes on the following: 
   - Demonstrate ability to read notes associated with Service Principal objects (#1)
   - Demonstrate ability to write note fields using application identity (#2)
   - Look up users by name using MS Graph API (#5)
   - Apply delta queries to notes field in Service Principal object (#15)
   - Create example of writing message to storage queue with visibility expiry (#26, #27)

- [x] Changes in plan versus last

 - Pending game plan review

- [x] Key design decisions and their outcomes

 - Moved from change feed to an additional storage queue which improves developer experience and provides more control explicitly contained within specific steps of the overall flow. (#6)

### Demo
- [x] Demo completed

### Key Project Risks and Concerns

- [x] Present Retro
 - Not yet completed, will have weekly retrospectives once in sprints.
- Complete list of [Scheduled Retros](https://github.com/retaildevcrews/ServicePrincipal/projects/1?card_filter_query=label%3ARetro) 

- [x] Engineering Fundamentals Assessment
- Engineering fundamentals have been built into game plan; will evaluate periodically throughout sprints
- Complete list of [Engineering Survey](https://github.com/retaildevcrews/ServicePrincipal/projects/1?card_filter_query=label%3ARetro)

- [x] Discuss open risks and mitigation plans
 - Given recent churn with another Walmart engagement, written approval/sign-off from Walmart Cloud Identity Team is needed

### Backlog Review

- [x] What is the planned for work in future sprints?
 - Game plan review is scheduled for 9/17
 - Terraform automation 
 - CI/CD integration  
 - Testing (Seed, sync, validation) and logging
 - [Complete Backlog](https://github.com/retaildevcrews/ServicePrincipal/projects/1)
 

- [x] Is additional checkpoint review needed?
 - Yes

- [x] Is additional Game Plan review needed?
 - Yes, Scheduled for September 17th

### Tasks

- [x] Upload checkpoint review to Artifact Hub
