### ISSUE TITLE
Refactor for Reusability

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ServicePrincipal#99]
## Description:
The code needs refactored to make it more easily extensible for future delta processing additions.  This refactor will create a Chain of Responsibility starting at the Function method for delta detection and tie it to a specific processor which will create a specific GraphHelper.  The dependencies will be:

> Azure Function - Specific Function for processing change
> ---> IDeltaProcessor - handles specific changes, constructs, and executes components for its chain
> ---> ---> IGraphHelper - handles specific directory types; ServicePrincipals in our case; 
> ---> ---> IDALReslover - for CosmosDB Access
> --->---> IQueueService - send update messages
> ---> ---> IKeyVaultService - KV access

### Tasks

- [ ] ~~Change IGraphHelper interface to return DirectoryObject types~~ <-- Now part of Issue #111
- [x] Add IDeltaProcessor interface
- [x] Add IDeltaProcessor abstract class with base configuration retrieval in construction
- [x] Add ServicePrincipalProcessor class
- [x] Add IDeltaProcessorResolver interface
- [x] Add DeltaProcessorResolver class
- [x] Construct and add DeltaProcessorResolver to builder
- [x] Construct and add ServicePrincipalProcessor to DeltaProcessorResolver
- [x] Add IDeltaProcessorResolver to Function methods
